### ISSUE TITLE
firefox赞助商logo溢出

### ISSUE THREAD

**Issue by gssxgss** [jsconfcn/hangjs#56]
![js](https://cloud.githubusercontent.com/assets/689868/2752837/8e81ce84-c920-11e3-9c21-8c708a7247fc.png)

感觉这块css写的略乱

```
#content #sponsors li 
-  float: left
+  width: 100%

#content #sponsors a img
+ display: block
```

[成为赞助商]的按钮再另写样式比较好。

**Comment by meteormatt** [comment]
:+1: 
现在用的好像是

``` CSS
#content .column img {
    max-width: 100%;
}
```
